name: CI
on: [push]
jobs:
  build:
    runs-on: windows
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: 22
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build