name: WarOS
version: '${version}'
main: de.tbodyowski.waros.Main
api-version: '1.20'
load: POSTWORLD
authors: [tbodyowski]
description: Minecraft War`s main operating system
commands:
  status:
    usage: /status <Status> <Color>
  guild:
    description: Guild command
  admin:
    description: Open an admin Inventory
    permission: waros.admin
    permission-message: Das darfst du leider nicht machen
  border:
    description: Manages multiple particle borders.
    usage: /border <create|setradius|setcenter|delete> <name> [radius]
    permissions:
      border.admin:
        description: Allows the player to create and manage particle borders.
        default: op
  vanish:
    description: Hide yourself from other Players
    usage: /vanish {Player}
    permission: waros.vanish