name: WarOS
version: '${version}'
main: de.tbodyowski.waros.Main
api-version: '1.20'
load: POSTWORLD
authors: [tbodyowski]
description: Minecraft War`s main operating system
commands:
  status:
    usage: /status <Status> <Color>
  guild:
    description: Guild command
  admin:
    description: Open an admin Inventory
    permission: waros.admin
    permission-message: Das darfst du leider nicht machen