name: PureOS
version: '${version}'
main: de.tbodyowski.pureos.Main
api-version: '1.21'
load: POSTWORLD
authors: [tbodyowski]
description: PureCraft`s main operating system
commands:
  status:
    usage: /status <Status> <Color>
  admin:
    description: Open an admin Inventory
    permission: pureos.admin
    permission-message: Das darfst du leider nicht machen
  vanish:
    description: Hide yourself from other Players
    usage: /vanish {Player}
    permission: pureos.vanish
  sit:
    description: Allows you to sit down
    usage: /sit