name: Build and Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '22'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: waros-1.0.jar
          path: build/libs/waros-1.0.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/waros-1.0.jar
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}